In [1]:
import numpy as np
import pandas as pd
import keras
import sklearn

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline

"""
- Da es sich um ein Regressionsproblem handelt, hat der Outputlayer keine Aktivierungsfunktion
- Der Optimizer Adam wird verwendet als wie im vorigen Bsp. bei MNIST Stochastic Gradient Descent SGD
- Loss Funktion wird mit means square error berechnet
"""

'\n- Da es sich um ein Regressionsproblem handelt, hat der Outputlayer keine Aktivierungsfunktion\n- Der Optimizer Adam wird verwendet als wie im vorigen Bsp. bei MNIST Stochastic Gradient Descent SGD\n- Loss Funktion wird mit means square error berechnet\n'

In [2]:
"Laden der Daten"

data = 'fake_job_postings.csv'

df = pd.read_csv(data)

df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [3]:
df_neu = pd.get_dummies(df)
df_neu

,job_id,telecommuting,has_company_logo,has_questions,fraudulent,title_ Electrician,title_ Environmental Technician I,title_ Piping Material Engineer,"title_ Discipline Manager Civil, Structural, Marine, Architectural",title_ FEA Senior engineer,...,function_Public Relations,function_Purchasing,function_Quality Assurance,function_Research,function_Sales,function_Science,function_Strategy/Planning,function_Supply Chain,function_Training,function_Writing/Editing
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,5,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,0,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17876,17877,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17877,17878,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17878,17879,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17879,17880,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
"Erstellung von Trainingsdaten und Testdaten"

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_neu, df_neu['fraudulent'], test_size=0.2, random_state=42, stratify=df_neu['fraudulent'])

In [5]:
x_test.shape

(3576, 51428)

In [6]:
"Standardscaler verwenden"

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
import keras
from keras.layers import Dense, Activation,Dropout
from keras.models import Sequential

model = Sequential()

model.add(Dense(128,activation  = 'relu',input_dim =x_test.shape[1]))
model.add(Dense(64,activation  = 'relu'))
model.add(Dense(32,activation  = 'relu'))
model.add(Dense(16,activation  = 'relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')

"""
Veränderung der Layergrösse --> siehe MNIST
"""

'\nVeränderung der Layergrösse --> siehe MNIST\n'

In [8]:
model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
447/447 [==============================] - 23s 50ms/step - loss: 0.0556
Epoch 2/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0277
Epoch 3/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0113
Epoch 4/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0050
Epoch 5/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0030
Epoch 6/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0026
Epoch 7/10
447/447 [==============================] - 22s 49ms/step - loss: 0.0018
Epoch 8/10
447/447 [==============================] - 22s 50ms/step - loss: 0.0015
Epoch 9/10
447/447 [==============================] - 22s 49ms/step - loss: 0.0021
Epoch 10/10
447/447 [==============================] - 22s 49ms/step - loss: 0.0022

In [9]:
#Evaluierung

y_pred = model.predict(x_test)

112/112 [==============================] - 1s 5ms/step

In [10]:
"Genauigkeit"
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(r2)

0.7003280393172624

In [11]:
"RMSE"

from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_pred)))
print(rmse)

0.11745718024223394